name: router
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pandas=2.3.3
  - pyarrow=21.0.0
  - arrow-cpp=21.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - icu=73.1
  - jansson=2.14
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libcxx=20.1.8
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libunistring=1.3
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy-base=2.3.5
  - numpy=2.3.5
  - openssl=3.0.18
  - orc=2.2.0
  - pip
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python=3.14.1
  - python_abi=3.14
  - pytz=2025.2
  - re2=2024.07.02
  - readline=8.3
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - utf8proc=2.6.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /opt/homebrew/anaconda3/envs/router
