modules:
  network:
    type: Network
    path: ../../output/v6.4/1pct/binpb-hor600/berlin-v6.4-1pct.network.binpb
  population:
    type: Population
    path: ../../output/v6.4/1pct/binpb-hor600/berlin-v6.4-1pct.plans.binpb
  vehicles:
    type: Vehicles
    path: ../../output/v6.4/1pct/binpb-hor600/berlin-v6.4-1pct.vehicles.binpb
  ids:
    type: Ids
    path: ../../output/v6.4/1pct/binpb-hor600/berlin-v6.4-1pct.ids.binpb
  partitioning:
    type: Partitioning
    num_parts: 10
    method: !Metis
      vertex_weight:
        - InLinkCount
      imbalance_factor: 1.1
      edge_weight: Capacity
  output:
    type: Output
    output_dir: ../../output/v6.4/1pct
    write_events: Proto
    logging: Info
    profiling: !Parquet
      level: TRACE
  routing:
    type: Routing
    mode: AdHoc
  simulation:
    type: Simulation
    start_time: 0
    end_time: 129600
    sample_size: 0.01
    stuck_threshold: 30
    main_modes:
      - car
      - freight
      - truck
  computational_setup:
    type: ComputationalSetup
    global_sync: false